export const pricingPlans = [
  {
    id: 'basic',
    name: 'Basic',
    monthlyPrice: 29,
    yearlyPrice: 290,
    description: 'Perfect for startups and small teams getting started.',
    popular: false,
    features: [
      'Up to 5 team members',
      '10 GB storage',
      'Basic analytics',
      'Email support',
      'API access',
      '1 project',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    monthlyPrice: 79,
    yearlyPrice: 790,
    description: 'Best for growing businesses that need more power.',
    popular: true,
    features: [
      'Up to 20 team members',
      '50 GB storage',
      'Advanced analytics',
      'Priority email & chat support',
      'Full API access',
      'Unlimited projects',
      'Custom integrations',
      'Team roles & permissions',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    monthlyPrice: 199,
    yearlyPrice: 1990,
    description: 'For large organizations with enterprise-grade needs.',
    popular: false,
    features: [
      'Unlimited team members',
      '500 GB storage',
      'Real-time analytics',
      '24/7 dedicated support',
      'Full API + SDK access',
      'Unlimited projects',
      'Custom integrations',
      'SSO & advanced security',
      'Dedicated account manager',
      'SLA guarantee',
    ],
  },
]
